# Generated by Django 6.0.1 on 2026-02-05 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoColaboradores',
            fields=[
                ('codigo_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cargo_colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('codigo_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colaborador', models.CharField(max_length=150)),
                ('usuario_sistema', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=50)),
                ('usuario_sentinel', models.CharField(max_length=15)),
                ('usuario_sbs', models.CharField(max_length=15)),
                ('usuario_windows', models.CharField(max_length=15)),
                ('usuario_reloj_control', models.CharField(max_length=15)),
                ('codigo_impresion_colaborador', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoColaboradores',
            fields=[
                ('codigo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=60)),
                ('descripcion_almacen', models.CharField(max_length=150)),
                ('direccion_almacen', models.CharField(max_length=120)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'almacences',
            },
        ),
        migrations.CreateModel(
            name='AreasEmpresa',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=40)),
                ('descripcion_area', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'areas_empresa',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoItems',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=60)),
                ('descripcion_estado', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_estado_items',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_item', models.CharField(max_length=100)),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='D:\\Proyectos y Cursos a Medias\\ProyectosPropios\\Python\\aplicaciones_incasur\\media\\qr')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.almacenes')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.areasempresa')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.colaboradores')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipoestadoitems')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='HistorialInventarios',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=40)),
                ('nombre_almacen', models.CharField(max_length=60)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.items')),
            ],
            options={
                'db_table': 'historial_inventarios',
            },
        ),
        migrations.CreateModel(
            name='ItemsEliminados',
            fields=[
                ('id_eliminados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=40)),
                ('nombre_almacen', models.CharField(max_length=60)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.items')),
            ],
            options={
                'db_table': 'items_eliminados',
            },
        ),
        migrations.CreateModel(
            name='ItemsMovimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_origen', models.CharField(max_length=150)),
                ('nombre_destino', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.items')),
            ],
            options={
                'db_table': 'items_movimientos',
            },
        ),
    ]
