# Generated by Django 6.0.1 on 2026-02-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_qr/'),
        ),
    ]
