# Generated by Django 6.0.1 on 2026-02-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0002_alter_items_imagen_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItems',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=60)),
                ('decripcion_tipo', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_items',
            },
        ),
        migrations.CreateModel(
            name='TiposMovimiento',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento', models.CharField(max_length=60)),
                ('decripcion_tipo', models.CharField(max_length=150)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_movimiento',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='cantidad_items',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='items',
            name='descripcion_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='id_movimiento_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.itemsmovimientos'),
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='observaciones',
            field=models.CharField(default='Sin Observaciones', max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.areasempresa'),
        ),
        migrations.CreateModel(
            name='ItemMovimientosCabecera',
            fields=[
                ('id_cabezera', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('firma_base64', models.TextField()),
                ('hash_seguridad', models.CharField(editable=False, max_length=64)),
                ('colaborador_confirma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_logistica.colaboradores')),
            ],
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='id_movimiento_cabezera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.itemmovimientoscabecera'),
        ),
        migrations.AddField(
            model_name='items',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipoitems'),
        ),
        migrations.AddField(
            model_name='itemsmovimientos',
            name='tipo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tiposmovimiento'),
        ),
        migrations.DeleteModel(
            name='ItemsEliminados',
        ),
    ]
