# Generated by Django 6.0.1 on 2026-02-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0003_tipoitems_tiposmovimiento_items_cantidad_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmovimientoscabecera',
            name='pdf_archivo',
            field=models.FileField(blank=True, null=True, upload_to='pdfs_movimientos/'),
        ),
    ]
