# Generated by Django 6.0.1 on 2026-02-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0004_itemmovimientoscabecera_pdf_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsmovimientos',
            name='cantidad_movimiento',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
