# Generated by Django 6.0.1 on 2026-02-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0005_itemsmovimientos_cantidad_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmovimientoscabecera',
            old_name='id_cabezera',
            new_name='id_cabecera',
        ),
        migrations.AlterModelTable(
            name='itemmovimientoscabecera',
            table='items_movimientos_cabezera',
        ),
    ]
