# Generated by Django 6.0.1 on 2026-03-15 04:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0007_proveedores_tipomoneda_remove_items_descripcion_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='documento',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
