# Generated by Django 6.0.1 on 2026-03-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0008_alter_items_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipoestadoitems'),
        ),
    ]
