# Generated by Django 6.0.1 on 2026-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0011_itemsmovimientos_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='id_area',
        ),
        migrations.RemoveField(
            model_name='historialinventarios',
            name='nombre_area',
        ),
        migrations.AlterField(
            model_name='itemsmovimientos',
            name='nombre_origen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='AreasEmpresa',
        ),
    ]
