# Generated by Django 6.0.1 on 2026-03-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0012_remove_items_id_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmovimientos',
            name='proveedor',
        ),
    ]
