# Generated by Django 6.0.1 on 2026-03-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0014_itemsmovimientos_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipoestadoitems'),
        ),
    ]
