# Generated by Django 6.0.1 on 2026-03-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0015_alter_items_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposInsumo',
            fields=[
                ('id_tipo_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=40)),
                ('cuenta_contable_haber', models.CharField(max_length=20)),
                ('cuenta_contable_debe', models.CharField(max_length=20)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_insumo',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='tipo_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tiposinsumo'),
        ),
    ]
