# Generated by Django 6.0.1 on 2026-03-31 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistica', '0016_tiposinsumo_items_tipo_insumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradores',
            options={'managed': False, 'ordering': ['nombre_colaborador']},
        ),
        migrations.AlterModelOptions(
            name='tiposmovimiento',
            options={'ordering': ['nombre_movimiento']},
        ),
        migrations.AlterField(
            model_name='items',
            name='tipo_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_logistica.tipomoneda'),
        ),
    ]
