# Generated by Django 6.0.1 on 2026-03-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=40)),
                ('detalle_proyecto', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=80)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'responsables',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_tarea', models.CharField(max_length=80)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seguimiento_actividades.proyectos')),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='SubTareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_subtarea', models.CharField(max_length=80)),
                ('inicio_actividad', models.DateTimeField()),
                ('fin_actividad', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seguimiento_actividades.proyectos')),
                ('responsable_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seguimiento_actividades.responsables')),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seguimiento_actividades.tareas')),
            ],
            options={
                'db_table': 'sub_tareas',
            },
        ),
    ]
