# Generated by Django 6.0.1 on 2026-03-05 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento_actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estado_tareas',
            },
        ),
        migrations.AlterField(
            model_name='subtareas',
            name='fin_actividad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subtareas',
            name='inicio_actividad',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='subtareas',
            name='estado_tareas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_seguimiento_actividades.estadotareas'),
        ),
        migrations.CreateModel(
            name='GestionSubtareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_gestion', models.TextField(max_length=400)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_subtarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seguimiento_actividades.subtareas')),
            ],
            options={
                'db_table': 'gestion_subtareas',
            },
        ),
    ]
