# Generated by Django 6.0.1 on 2026-03-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento_actividades', '0003_alter_subtareas_detalle_subtarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtareas',
            name='detalle_subtarea',
            field=models.TextField(max_length=350),
        ),
    ]
